name: flutter_absensi_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  camera: ^0.11.0
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.11.0
  http: ^1.2.1
  image: ^4.2.0
  image_picker: ^1.1.1
  intl: 0.17.0
  location: ^6.0.2
  permission_handler: 8.2.2
  shared_preferences: ^2.2.3
  tflite_flutter: ^0.10.4
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/
    - assets/icons/logo/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
